---

- import_tasks: os-vars.yml
  tags:
    - cantaloupe
    - cantaloupe-config
    - cantaloupe-install

- include_tasks: "install-{{ ansible_os_family }}.yml"
  tags:
    - cantaloupe
    - cantaloupe-install

- import_tasks: config.yml
  tags:
    - cantaloupe
    - cantaloupe-config

- import_tasks: web.yml
  tags:
    - cantaloupe
    - cantaloupe-web
  when: cantaloupe_deploy_war

- import_tasks: cache.yml
  tags:
    - cantaloupe
    - cantaloupe-cache
  when: cantaloupe_create_FilesystemCache_dir
