---
all:
  vars:
    ansible_user: runner
    islandora_build_base_box: false
    islandora_distro: ubuntu/jammy64
    islandora_profile: starter
  children:
    alpaca:
      hosts:
        localhost:
          ansible_connection: local
    crayfish:
      hosts:
        localhost:
          ansible_connection: local
    database:
      hosts:
        localhost:
          ansible_connection: local
    solr:
      hosts:
        localhost:
          ansible_connection: local
    tomcat:
      hosts:
        localhost:
          ansible_connection: local
    webserver:
      hosts:
        localhost:
          ansible_connection: local
