---

- name: Ensure Alpaca directory exists
  file:
    path: "{{ alpaca_clone_directory }}"
    state: directory
    owner: "{{ alpaca_user }}"
    group: "{{ alpaca_group }}"

- name: Check for alpaca jar
  ansible.builtin.stat:
    path: "{{ alpaca_jar_path }}"
  register: alpaca_jar_stat
    
- name: Download from Maven
  ansible.builtin.get_url:
    url: "https://repo1.maven.org/maven2/ca/islandora/alpaca/islandora-alpaca-app/{{ alpaca_version }}/islandora-alpaca-app-{{ alpaca_version }}-all.jar"
    dest: "{{ alpaca_jar_path }}"
    mode: "0644"
  when: not alpaca_jar_stat.stat.exists
