---

- hosts: crayfish
  become: yes

  roles:
    - role: geerlingguy.repo-remi
      when: "ansible_os_family == 'RedHat' and islandora_build_base_box|bool == True"
    - role: geerlingguy.apache  # Include apache to get the handlers
    - role: geerlingguy.php-versions
      when: islandora_build_base_box|bool == True
    - role: geerlingguy.php
      when: islandora_build_base_box|bool == True
    - role: geerlingguy.php-mysql
      when: islandora_build_base_box|bool == True
    - role: geerlingguy.git
      when: islandora_build_base_box|bool == True
    - role: geerlingguy.composer
      when: islandora_build_base_box|bool == True

    - role: Islandora-Devops.crayfish
      when: islandora_build_base_box|bool == False
