---

- hosts: database
  become: yes

  pre_tasks:
    - name: Just set the database type to mysql
      set_fact:
        islandora_db: 'mysql'
      when: islandora_db is not defined
      tags:
        - always

  roles:
    - role: geerlingguy.mysql
      when: "islandora_build_base_box|bool == True and islandora_db == 'mysql'"
    - role: geerlingguy.postgresql
      when: "islandora_build_base_box|bool == True and islandora_db == 'pgsql'"