---

- hosts: database
  become: yes

  pre_tasks:
    - set_fact:
        islandora_db: 'mysql'
      when: islandora_db is not defined
      tags:
        - always

  roles:
    - role: geerlingguy.mysql
      when: islandora_db == 'mysql'
    - role: geerlingguy.postgresql
      when: islandora_db == 'pgsql'
