- name: Adding extra packages for the RDM system
  hosts: webserver
  become: yes

  vars:
    rdm_drupal_composer_dependencies:
      - "dompdf/dompdf:*"
      - "drupal/conditional_fields:*"
      - "drupal/markup:*"
      - "drupal/select_or_other:*"
      - "drupal/dynamic_entity_reference:2.0-alpha9"
      - "drupal/clamav:*"
      - "drupal/entity_print:*"
      - "drupal/simple_sitemap:*"
      - "islandora-rdm/islandora_rdm:dev-8.x-1.x"
      - "islandora-rdm/islandora_rdm_defaults:dev-8.x-1.x"
      - "islandora-rdm/islandora_rdm_multifile_media:dev-8.x-1.x"
      - "drupal/orcid:1.x-dev"
      - "drupal/tus:1.x-dev"
      - "drupal/uppy:1.x-dev"
      - "islandora-rdm/csv_field_preview"
      - "drupal/readonly_field_widget:^1.3"
      - "drupal/matomo_reports:^1.0"
      - "drupal/gdpr:*"
      - "drupal/eu_cookie_compliance:*"
      - 'drupal/entity_reference_unpublished:^1.1'
      - 'islandora_datacite_doi:dev-8.x-1.x'

    rdm_drupal_enable_modules:
      - entity_reference_unpublished
      - conditional_fields
      - markup
      - select_or_other
      - clamav
      - entity_print
      - simple_sitemap
      - matomo_reports
      - islandora_rdm
      - islandora_rdm_defaults
      - eu_cookie_compliance

    rdm_drupal_enable_modules2:
      - islandora_rdm_multifile_media
      - islandora_rdm_media_types
      - islandora_rdm_site
      - islandora_rdm_data_management_plan
      - islandora_rdm_workflows
      - orcid
      - tus
      - uppy
      - csv_field_preview
      - readonly_field_widget
      - islandora_rdm_file_transmission_fixity
      - gdpr
      - islandora_rdm_solr_config


  tasks:
    - name: Ubuntu packages for RDM
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - php7.2-zip
      when: ansible_os_family == "Debian"

    #    Our file model requires FITS methods not present in base islandora_fits
    - name: Set git email
      command: git config --global user.email user@example.com

    - name: Set FITS branch
      command: "git checkout newFileModel"
      args:
        chdir: "{{ drupal_core_path }}/modules/contrib/islandora_fits"
      ignore_errors: yes
      become_user: root

    - name: Pull FITS branch
      command: "git pull origin newFileModel"
      args:
        chdir: "{{ drupal_core_path }}/modules/contrib/islandora_fits"
      become_user: root

    - name: Check Deployment Addresses
      command: "sed -i 's/8000/{{ apache_listen_port }}/g' /opt/karaf/deploy/{{ item }}"
      with_items:
        - ca.islandora.alpaca.connector.fits.blueprint.xml
        - ca.islandora.alpaca.connector.ocr.blueprint.xml
      become_user: root

    - name: Enable patching in composer
      composer:
        command: config
        working_dir: "{{ drupal_composer_install_dir }}"
        arguments: extra.enable-patching true

    - name: Download drupal core patch.
      get_url:
        url: https://www.drupal.org/files/issues/2020-02-02/2890844-65.drupal.patch
        dest: /tmp/2890844-65.drupal.patch

    - name: Apply the patch from the drupal docroot.
      shell: "patch -p1 < /tmp/2890844-65.drupal.patch chdir=/var/www/html/drupal/web"
      ignore_errors: yes

    - name: Install RDM dependencies with composer require (this may take a while).
      composer:
        command: require
        arguments: "{{ item }}"
        working_dir: "{{ drupal_composer_install_dir }}"
      with_items: "{{ rdm_drupal_composer_dependencies|default([]) }}"
      become: no

    - name: Install RDM configured modules with drush.
      command: "{{ drush_path }} --root=/var/www/html/drupal/web -y en {{ rdm_drupal_enable_modules | join(' ') }}"
    - name: Install RDM configured modules with drush2.
      command: "{{ drush_path }} --root=/var/www/html/drupal/web -y en {{ rdm_drupal_enable_modules2 | join(' ') }}"
    #      ignore_errors: yes

    - name: Import RDM features
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y fim islandora_rdm_types,islandora_rdm_data_management_plan,islandora_rdm_defaults,islandora_rdm_media_types --bundle=islandora_rdm"

    #    - name: Set ORCID client_id
    #      command: "{{ drush_path }} --root {{ drupal_core_path }} cset orcid.settings client_id {{ orcid_client_id }} -y"
    #      when: orcid_client_id is defined and orcid_client_id  != ''

    #    - name: Set ORCID client_secret
    #      command: "{{ drush_path }} --root {{ drupal_core_path }} cset orcid.settings client_secret {{ orcid_client_secret }} -y"
    #      when: orcid_client_secret is defined and orcid_client_secret  != ''

    - name: Set ORCID name field
      command: "{{ drush_path }} --root {{ drupal_core_path }} cset orcid.settings name_field field_orcid_id  -y"

    - name: Uninstall Tus
      command: "{{ drush_path }} --root=/var/www/html/drupal/web  pm-uninstall tus  -y"

    - name: Reinstall Tus
      command: "{{ drush_path }} --root=/var/www/html/drupal/web   en tus  -y"

    - name: Set TUS Scheme
      command: "{{ drush_path }} --root {{ drupal_core_path }} cset tus.settings scheme public://  -y"


