- src: geerlingguy.php-mysql
  version: 2.0.1

- src: geerlingguy.repo-remi
  version: 1.2.0

- src: geerlingguy.apache
  version: 3.0.0

- src: geerlingguy.php-versions
  version: 2.1.5

- src: geerlingguy.php
  version: 3.6.0

- src: geerlingguy.composer
  version: 1.7.0

- src: geerlingguy.git
  version: 2.0.2

- src: geerlingguy.mysql
  version: 2.9.0

- src: geerlingguy.postgresql
  version: 1.4.3

- src: geerlingguy.solr
  version: 4.2.1

- src: geerlingguy.java
  version: 1.8.1

- src: geerlingguy.drupal
  version: 2.5.0

- src: geerlingguy.drush
  version: 3.1.1

- src: geerlingguy.drupal-console
  version: 1.1.1

- src: https://github.com/Islandora-Devops/ansible-role-activemq
  name: Islandora-Devops.activemq
  version: 1.0.0

- src: https://github.com/Islandora-Devops/ansible-role-alpaca
  name: Islandora-Devops.alpaca
  version: 1.0.0

#- src: https://github.com/Islandora-Devops/ansible-role-apix
#  name: Islandora-Devops.apix
#  version: 0.0.1

- src: https://github.com/Islandora-Devops/ansible-role-blazegraph
  name: Islandora-Devops.blazegraph
  version: 1.0.0

- src: https://github.com/Islandora-Devops/ansible-role-cantaloupe
  name: Islandora-Devops.cantaloupe
  version: 1.0.0

- src: https://github.com/Islandora-Devops/ansible-role-crayfish
  name: Islandora-Devops.crayfish
  version: 1.0.0

- src: https://github.com/Islandora-Devops/ansible-role-drupal-openseadragon
  name: Islandora-Devops.drupal-openseadragon
  version: 1.0.0

- src: https://github.com/Islandora-Devops/ansible-role-fcrepo
  name: Islandora-Devops.fcrepo
  version: 1.0.0

- src: https://github.com/Islandora-Devops/ansible-role-fcrepo-syn
  name: Islandora-Devops.fcrepo-syn
  version: 1.0.0

- src: https://github.com/Islandora-Devops/ansible-role-tomcat8
  name: Islandora-Devops.tomcat8
  version: 1.0.0

- src: https://github.com/Islandora-Devops/ansible-role-fits
  name: Islandora-Devops.fits
  version: 1.0.0

- src: https://github.com/Islandora-Devops/ansible-role-grok
  name: Islandora-Devops.grok
  version: 1.0.0

- src: https://github.com/Islandora-Devops/ansible-role-karaf
  name: Islandora-Devops.karaf
  version: 1.0.0

- src: https://github.com/Islandora-Devops/ansible-role-keymaster
  name: Islandora-Devops.keymaster
  version: 1.0.0

- src: https://github.com/Islandora-Devops/ansible-role-matomo
  name: Islandora-Devops.matomo
  version: 1.0.0
