---
- src: geerlingguy.php-mysql
  version: 2.1.0

- src: geerlingguy.repo-epel
  version: 3.1.1

- src: geerlingguy.repo-remi
  version: 2.1.0

- src: geerlingguy.apache
  version: 4.2.0

- src: geerlingguy.php-versions
  version: 7.0.1

- src: geerlingguy.php
  version: 6.0.0

- src: geerlingguy.composer
  version: 1.9.2

- src: geerlingguy.git
  version: 3.0.1

- src: geerlingguy.mysql
  version: 6.3.1

- src: geerlingguy.postgresql
  version: 4.0.3

- src: geerlingguy.solr
  version: 6.0.0

- src: geerlingguy.java
  version: 2.6.0

- src: geerlingguy.drupal
  version: 4.3.0
