---

- hosts: webserver
  become: yes

  environment:
    COMPOSER_MEMORY_LIMIT: -1

  roles:
    - name: geerlingguy.repo-remi
      when: "ansible_os_family == 'RedHat' and islandora_build_base_box|bool == True"
    - name: geerlingguy.apache
      when: islandora_build_base_box|bool == True
    - name: geerlingguy.php-versions
      when: islandora_build_base_box|bool == True
    - name: geerlingguy.php
      when: islandora_build_base_box|bool == True
    - name: geerlingguy.php-mysql
      when: islandora_build_base_box|bool == True
    - name: geerlingguy.git
      when: islandora_build_base_box|bool == True
    - name: geerlingguy.composer
      when: islandora_build_base_box|bool == True
    - name: geerlingguy.drush  # Include drush as drupal-openseadragon needs it.
      when: islandora_build_base_box|bool == False

    - name: geerlingguy.drupal
      when: islandora_build_base_box|bool == False
    - name: perms-fix
      when: islandora_build_base_box|bool == False
    - name: Islandora-Devops.drupal-openseadragon
      when: islandora_build_base_box|bool == False
    - name: webserver-app
      when: islandora_build_base_box|bool == False
    - name: Islandora-Devops.matomo
      when: "webserver_install_matomo and islandora_build_base_box|bool == False"
