---

- set_fact: crayfish_loop="{{ item }}"

- name: Verify/Create Symfony config directories
  file:
    state: directory
    dest: '{{ crayfish_install_dir }}/{{ crayfish_loop }}/config/{{ item_path.path }}'
  with_filetree: '../templates/{{ crayfish_loop }}'
  loop_control:
    loop_var: 'item_path'
  when: item_path.state == 'directory'

- name: Template Symfony config files
  template:
    src: '{{ item_path.src }}'
    dest: '{{ crayfish_install_dir }}/{{ crayfish_loop }}/config/{% if item_path.path.endswith(".j2") %}{{ item_path.path[:-3] }}{% else %}{{ item_path.path }}{% endif %}'
  with_filetree: '../templates/{{ crayfish_loop }}'
  loop_control:
    loop_var: item_path
  when: item_path.state == 'file'
