- name: Download fcrepo war
  get_url:
    url: https://github.com/fcrepo4-exts/fcrepo-webapp-plus/releases/download/fcrepo-webapp-plus-{{ fcrepo_version }}/fcrepo-webapp-plus-{{ fcrepo_version }}.war
    dest: "{{ fcrepo_war_path }}"
    owner: "{{ fcrepo_user }}"
    group: "{{ fcrepo_user }}"

- name: Create fcrepo data directory
  file:
    path: "{{ fcrepo_data_dir }}"
    state: directory
    owner: "{{ fcrepo_user }}"
    group: "{{ fcrepo_user }}"

- name: Create fcrepo home directory
  file:
    path: "{{ fcrepo_home_dir }}"
    state: directory
    owner: "{{ fcrepo_user }}"
    group: "{{ fcrepo_user }}"

- name: Create fcrepo config directory
  file:
    path: "{{ fcrepo_home_dir }}/configs"
    state: directory
    owner: "{{ fcrepo_user }}"
    group: "{{ fcrepo_user }}"
