---
dependency:
  name: galaxy
  options:
    role-file: ../../requirements.yml
    roles-path: ../../roles/external

driver:
  name: default

lint: {}

platforms: []

provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: ../../roles/external:../../roles/internal
  inventory:
    links:
      hosts: inventory/hosts.yml
  playbooks:
    converge: converge.yml
  env:
    ANSIBLE_CONFIG: ../../ansible.cfg

scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
