---
driver:
  name: default

platforms:
  - name: localhost

provisioner:
  name: ansible
  inventory:
    links:
      hosts: inventory/hosts.yml
  playbooks:
    converge: converge.yml
  env:
    ANSIBLE_CONFIG: ../../ansible.cfg

scenario:
  name: default
  test_sequence:
    - syntax
