---
# renovate: datasource=github-releases depName=scyllaridae packageName=islandora/scyllaridae
scyllaridae_version: "5.2.1"

scyllaridae_services:
  - Crayfits
  - Hypercube
  - Homarus
  - Houdini

scyllaridae_install_dir: /opt/scyllaridae
scyllaridae_log_directory: /var/log/islandora
scyllaridae_log_level: info
