---

  - name: Explicitly allow composer plugins for drupal
    community.general.composer:
      command: config
      global_command: true
      arguments: "allow-plugins.{{ item }} true"
    loop:
      - composer/installers
      - drupal/core-composer-scaffold
      - drupal/core-project-message
      - zaporylie/composer-drupal-optimizations
