---

- name: Look for drush in expected path
  ansible.builtin.stat:
    path: "/usr/local/bin/drush"
  register: drush_stat

- name: Use found drush instead
  set_fact: drush_path="/usr/local/bin/drush"
  when: drush_path is not defined and drush_stat.stat.exists

- import_tasks: apache.yml
  when: webserver_app_apache
  tags:
    - webserver-app
    - webserver-app-apache

- import_tasks: drupal.yml
  when: webserver_app_drupal
  tags:
    - webserver-app
    - webserver-app-drupal

- import_tasks: jwt.yml
  when: webserver_app_jwt
  tags:
    - webserver-app
    - webserver-app-jwt

- import_tasks: solr.yml
  when: webserver_app_drupal
  tags:
    - webserver-app
    - webserver-app-drupal

