---

- include: "define-home.yml"
  tags:
    - tomcat9
    - tomcat9-config
    - tomcat9-install
  
- include: "install-{{ ansible_os_family }}.yml"
  tags:
    - tomcat9
    - tomcat9-install

- include_tasks: config.yml
  tags:
    - tomcat9
    - tomcat9-config
