- import_tasks: install.yml
  tags:
    - fcrepo
    - fcrepo-install

- import_tasks: db-mysql.yml
  when: fcrepo_db_type == 'mysql' or fcrepo_persistence == 'jdbc-mysql'
  tags:
    - fedora
    - fedora-install
    - fedora-db

- import_tasks: db-pgsql.yml
  when: fcrepo_db_type == 'postgresql' or fcrepo_persistence == 'jdbc-postgresql'
  become: yes
  tags:
    - fedora
    - fedora-install
    - fedora-db

- import_tasks: config.yml
  tags:
    - fcrepo
    - fcrepo-config
