---

- name: Download ActiveMQ
  get_url:
    url: http://archive.apache.org/dist/activemq/{{ activemq_version }}/apache-activemq-{{ activemq_version }}-bin.tar.gz
    dest: "{{ activemq_install_root }}"
    owner: "{{ activemq_user }}"
    timeout: 300

- name: Expand ActiveMQ
  unarchive:
    src: "{{ activemq_install_root }}/apache-activemq-{{ activemq_version }}-bin.tar.gz"
    dest: "{{ activemq_install_root }}"
    copy: false
    owner: "{{ activemq_user }}"
    group: "{{ activemq_user }}"

- name: Make ActiveMQ symlink
  file:
    src: "{{ activemq_install_root }}/apache-activemq-{{ activemq_version }}"
    dest: "{{ activemq_install_root }}/activemq"
    owner: "{{ activemq_user }}"
    group: "{{ activemq_user }}"
    state: link

- name: Cleanup ActiveMQ archive file
  file:
    path: "{{ activemq_install_root }}/apache-activemq-{{ activemq_version }}-bin.tar.gz"
    state: absent


# Transitional removal of old-style init.d symlink
# This task can be removed in the future.
- name: Remove init.d symlink
  file:
    path: /etc/init.d/activemq
    state: absent

- name: Create systemd unit
  template:
    src: activemq.service.j2
    dest: /etc/systemd/system/activemq.service

- name: Reload systemd
  systemd:
    daemon-reload: yes
    enabled: yes
    state: started
    name: activemq
