---
- include: os-vars.yml
  tags:
    - fcrepo-syn
    - fcrepo-syn-config
    - fcrepo-syn-install

- include: install.yml
  tags:
    - fcrepo-syn
    - fcrepo-syn-install

- name: Show ansible_os_family
  debug:
    msg: "ansible_os_family: {{ ansible_os_family }}"

- include: "config-{{ ansible_os_family }}.yml"
  tags:
    - fcrepo-syn
    - fcrepo-syn-config
