---
- import_tasks: "define-home.yml"
  tags:
    - blazegraph
    - blazegraph-config
    - blazegraph-install

- include_tasks: "install-{{ ansible_os_family }}.yml"
  tags:
    - blazegraph
    - blazegraph-install

- import_tasks: download.yml
  tags:
    - blazegraph
    - blazegraph-download

- import_tasks: logging.yml
  tags:
    - blazegraph
    - blazegraph-logging

- include_tasks: "config-{{ ansible_os_family }}.yml"
  tags:
    - blazegraph
    - blazegraph-config

- import_tasks: namespace.yml
  tags:
    - blazegraph
    - blazegraph-namespace
